# git에 올리면 안됨(gitignore)




spring:
  security:
    oauth2:
      client:
        registration:

          google:
            client-id: 119844155070-d48oov1fr74qco01604l1ge619o14r6g.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            client-name: Google
            scope:
              - email
              - profile
          kakao:
            client-id: e07bb4b8d5b0f2531b6c6721df5ac8eb #본인 RestAPI 키
            client-secret: AAv7JC8SEeWvi2O25iERwjW6LX3xNvkL #본인 secret 키
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
          naver:
            client-id: Z9z3XtS3_Aa7O41NNIG9 #본인 RestAPI 키
            client-secret:  D8xw86rBqi #본인 secret 키
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  #이메일 인증
  mail:
    host: smtp.naver.com
    port: 587
    username: inkyum77@naver.com
    password: 5HDH1Q287KPN
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: camping




  datasource: 
    url: jdbc:mysql://localhost:3306/ictedu_db
    username: ictedu
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

# 정적 파일(이미지, css, js 등)을 URL로 접근할 수 있도록 설정하는 옵션
# http://localhost:8080/{파일명}
  web:
    resources:
      static-locations: file:C:/upload
      # static-locations: classpath:/static/

# twilio 문자 인증
twilio:
  account-sid: ACd5f9a1f5ac6f9db9d9afe2a7cb046c1b
  auth-token: dfad46fc4621945acceb30a8cb07381b
  phone-number: +12184344815

server:
  port: 8080
  servlet:
    context-path: /


mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.ict.camping

#비밀키 사용(32byte)
jwt:
  secret: "ab1CdEFg5fyjkLmNOpqrsTuvW8xYz123vsdvasdsdca"
  expiration: 3600000



logging:
  level:
    org.springframework.mail: DEBUG

file:
  upload-dir: C:/upload